version: "2"

services:
  postgres:
    environment:
      - POSTGRES_USER=crawlr
      - POSTGRES_PASSWORD=crawlr
    image: postgres
    ports:
     - "5432:5432"

  redis:
    image: redis:alpine
    ports:
     - "6379:6379"
